/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class KHS extends javax.swing.JFrame {

    /**
     * Creates new form KHS
     */
    public KHS() {
        initComponents();
    }
    void urutHuruf(KeyEvent a){
        char karakter = a.getKeyChar();
        if(!((karakter >= '0')&&(karakter <= '9')||(karakter == KeyEvent.VK_BACK_SPACE)||(karakter == KeyEvent.VK_DELETE) || (karakter == KeyEvent.VK_ENTER))){
            getToolkit().beep();
            a.consume();
            JOptionPane.showMessageDialog(null,"inputan hanya angka saja","Peringatan",1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        nim = new javax.swing.JTextField();
        progdi = new javax.swing.JTextField();
        jml_sks = new javax.swing.JTextField();
        ips = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        matkul = new javax.swing.JComboBox<>();
        sks = new javax.swing.JTextField();
        tugas = new javax.swing.JTextField();
        uts = new javax.swing.JTextField();
        uas = new javax.swing.JTextField();
        akhir = new javax.swing.JTextField();
        huruf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_mhs = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnBaru = new javax.swing.JButton();
        btnBersih = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Nama");

        jLabel2.setText("NIM");

        jLabel3.setText("Program Studi");

        jLabel4.setText("Jumlah SKS & IPS");

        nama.setEnabled(false);

        nim.setEnabled(false);

        progdi.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jml_sks, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(ips, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(progdi))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jml_sks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ips, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        matkul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~Mata Kuliah~", "Kewirausahaan", "PAI", "PKN", "Basis Data Lanjut", "PBO 1", "Pemrograman Mobile 1", "Pemrogrman GIS" }));
        matkul.setEnabled(false);
        matkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matkulActionPerformed(evt);
            }
        });

        sks.setEnabled(false);

        tugas.setEnabled(false);
        tugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tugasActionPerformed(evt);
            }
        });
        tugas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tugasKeyTyped(evt);
            }
        });

        uts.setEnabled(false);
        uts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utsActionPerformed(evt);
            }
        });
        uts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                utsKeyTyped(evt);
            }
        });

        uas.setEnabled(false);
        uas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uasActionPerformed(evt);
            }
        });
        uas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uasKeyTyped(evt);
            }
        });

        akhir.setEnabled(false);

        huruf.setEnabled(false);

        tbl_mhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mata Kuliah", "SKS", "Tugas", "UTS", "UAS", "Akhir", "Huruf"
            }
        ));
        jScrollPane1.setViewportView(tbl_mhs);

        btnTambah.setText("Tambah");
        btnTambah.setEnabled(false);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel7.setText("Mata Kuliah");

        jLabel8.setText("SKS");

        jLabel9.setText("Tugas");

        jLabel10.setText("UTS");

        jLabel11.setText("UAS");

        jLabel12.setText("N.Akhir");

        jLabel13.setText("N.Huruf");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matkul, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sks, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tugas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(uas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(akhir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(huruf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(akhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(huruf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnHapus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnBaru.setText("Baru");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        btnBersih.setText("Bersih");
        btnBersih.setEnabled(false);
        btnBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(btnBaru)
                .addGap(43, 43, 43)
                .addComponent(btnBersih)
                .addGap(43, 43, 43)
                .addComponent(btnKeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaru)
                    .addComponent(btnBersih)
                    .addComponent(btnKeluar))
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel6.setText("KHS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(284, 284, 284)
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tblKhs = (DefaultTableModel) tbl_mhs.getModel();
        tbl_mhs.setAutoCreateColumnsFromModel(true);
        List list = new ArrayList<>();
        int jmlBaris,sksQ,sksTotal=0;
        String hrf;
        double bbot,bbtTotal=0,bbtSks,totalIps;
        
        list.add(matkul.getSelectedItem().toString());
        list.add(sks.getText().toString());
        list.add(tugas.getText().toString());
        list.add(uts.getText().toString());
        list.add(uas.getText().toString());
        list.add(akhir.getText().toString());
        list.add(huruf.getText().toString());
        tblKhs.addRow(list.toArray());
        
        jmlBaris = tblKhs.getRowCount();
        
        for (int i = 0; i < jmlBaris; i++) {
            sksQ = Integer.valueOf(tblKhs.getValueAt(i, 1).toString());
            sksTotal = sksTotal + sksQ;
            
            hrf = tblKhs.getValueAt(i, 6).toString();
            if (hrf.equals("A")){
                bbot = 4.0;
            } else if (hrf.equals("AB")){
                bbot = 3.5;
            } else if (hrf.equals("B")){
                bbot = 3.0;
            } else if (hrf.equals("BC")){
                bbot = 2.5;
            } else if (hrf.equals("C")){
                bbot = 2.0;
            } else if (hrf.equals("D")){
                bbot = 1.0;
            } else {
                bbot = 0.0;
            }
            bbtSks = bbot * sksQ;
            bbtTotal = bbtTotal + bbtSks;
            
        }
        
        totalIps = bbtTotal / sksTotal;
        
        jml_sks.setText(String.valueOf(sksTotal));
        ips.setText(String.valueOf(totalIps));
        matkul.setSelectedIndex(0);
        sks.setText("");
        tugas.setText("");
        uts.setText("");
        uas.setText("");
        akhir.setText("");
        huruf.setText("");
        
        btnHapus.setEnabled(true);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void matkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matkulActionPerformed
        // TODO add your handling code here:
        String nimKHS,namaKHS,programStudiKHS;
        
        nimKHS = nim.getText();
        namaKHS = nama.getText();
        programStudiKHS = progdi.getText();
        
        if (nimKHS.equalsIgnoreCase("") || namaKHS.equalsIgnoreCase("") || programStudiKHS.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null,"Pastikan mengisi semua inputan yang tersedia","Peringatan",1);
            matkul.setSelectedIndex(0);
        }else{
            switch(matkul.getSelectedIndex()){
                case 0: sks.setText("");
                        tugas.setEnabled(false);
                        uts.setEnabled(false);
                        uas.setEnabled(false);
                        break;
                case 1: sks.setText("2");
                        tugas.setEnabled(true);
                        tugas.requestFocus();
                        break;
                case 2: sks.setText("2");
                        tugas.setEnabled(true);
                        tugas.requestFocus();
                        break;
                case 3: sks.setText("2");
                        tugas.setEnabled(true);
                        tugas.requestFocus();
                        break;
                case 4: sks.setText("4");
                        tugas.setEnabled(true);
                        tugas.requestFocus();
                        break;
                case 5: sks.setText("4");
                        tugas.setEnabled(true);
                        tugas.requestFocus();
                        break;
                case 6: sks.setText("4");
                        tugas.setEnabled(true);
                        tugas.requestFocus();
                        break;
                case 7: sks.setText("4");
                        tugas.setEnabled(true);
                        tugas.requestFocus();
                        break;
                default: JOptionPane.showMessageDialog(null,"Data tidak bisa ditemukan","Peringatan",1);
                        tugas.setEnabled(false);
                        break;
            }
        }
    }//GEN-LAST:event_matkulActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int selectedRow,opsi,jmlBaris;
        DefaultTableModel tblKhs = (DefaultTableModel) tbl_mhs.getModel();
        selectedRow = tbl_mhs.getSelectedRow();
        if (selectedRow >= 0) {
            opsi = JOptionPane.showConfirmDialog(null, "Apa benar akan dihapus?", "Peringatan", JOptionPane.YES_NO_OPTION);
            if (opsi == JOptionPane.YES_OPTION) {
                tblKhs.removeRow(selectedRow);
            }
        }
        jmlBaris = tblKhs.getRowCount();
        if (jmlBaris <= 0) {
            btnHapus.setEnabled(false);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        // TODO add your handling code here:
        nim.setEnabled(true);
        nim.requestFocus();
        nama.setEnabled(true);
        progdi.setEnabled(true);
        matkul.setEnabled(true);
        btnBaru.setEnabled(false);
        btnBersih.setEnabled(true);
    }//GEN-LAST:event_btnBaruActionPerformed

    private void btnBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblKhs = (DefaultTableModel) tbl_mhs.getModel();
        matkul.setSelectedIndex(0);
        nim.setText("");
        nama.setText("");
        progdi.setText("");
        jml_sks.setText("");
        ips.setText("");
        sks.setText("");
        tugas.setText("");
        tugas.setEnabled(false);
        uts.setText("");
        uas.setText("");
        akhir.setText("");
        huruf.setText("");
        btnTambah.setEnabled(false);
        if (tblKhs.getRowCount() > 0) {
            for (int i = tblKhs.getRowCount() - 1; i > -1; i--) {
                tblKhs.removeRow(i);
            }
            btnHapus.setEnabled(false); 
        }
        btnHapus.setEnabled(false);
        nim.requestFocus();
    }//GEN-LAST:event_btnBersihActionPerformed

    private void tugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tugasActionPerformed
        // TODO add your handling code here:
         int nTugas;
        nTugas = Integer.parseInt(tugas.getText().toString());
        if (nTugas > 100) {
            JOptionPane.showMessageDialog(null,"Nilai tidak boleh lebih dari 100","Peringatan",1);
        }else{
            uts.setEnabled(true);
            uts.requestFocus();
        }
    }//GEN-LAST:event_tugasActionPerformed

    private void utsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utsActionPerformed
        // TODO add your handling code here:
        int nUTS;
        nUTS = Integer.parseInt(uts.getText().toString());
        if (nUTS > 100) {
            JOptionPane.showMessageDialog(null,"Nilai tidak boleh lebih dari 100","Peringatan",1);
        }else{
            uas.setEnabled(true);
            uas.requestFocus();
        }
    }//GEN-LAST:event_utsActionPerformed

    private void uasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uasActionPerformed
        // TODO add your handling code here:
        int nUAS,nTugas,nUTS,nilaiUasCheck;
        double nAkhir;
        String hruf;
        nilaiUasCheck = Integer.parseInt(uas.getText().toString());
        if (nilaiUasCheck > 100) {
            JOptionPane.showMessageDialog(null,"Nilai tidak boleh lebih dari 100","Peringatan",1);
        }else{
            if (tugas.getText().isEmpty()) {
                nTugas = 0;
            }else{
                nTugas = Integer.parseInt(tugas.getText().toString());
            }
            if (uts.getText().isEmpty()) {
                nUTS = 0;
            }else{
                nUTS = Integer.parseInt(uts.getText().toString());
            }
            if (uas.getText().isEmpty()) {
                nUAS = 0;
            }else{
                nUAS = Integer.parseInt(uas.getText().toString());
            }
            nAkhir = (0.2 * nTugas) + (0.3 * nUTS) + (0.5 * nUAS);
            akhir.setText(String.valueOf(nAkhir));
            if (nAkhir>=85){
                hruf = "A";
            } else if (nAkhir>=80){
                hruf = "AB";
            } else if (nAkhir>=70){
                hruf = "B";
            } else if (nAkhir>=65){
                hruf = "BC";
            } else if (nAkhir>=60){
                hruf = "C";
            } else if (nAkhir>=50){
                hruf = "D";
            } else {
                hruf = "E";
            }
            huruf.setText(hruf);
            btnTambah.setEnabled(true);
        }
    }//GEN-LAST:event_uasActionPerformed

    private void tugasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tugasKeyTyped
        // TODO add your handling code here:
        urutHuruf(evt);
    }//GEN-LAST:event_tugasKeyTyped

    private void utsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_utsKeyTyped
        // TODO add your handling code here:
        urutHuruf(evt);
    }//GEN-LAST:event_utsKeyTyped

    private void uasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uasKeyTyped
        // TODO add your handling code here:
        urutHuruf(evt);
    }//GEN-LAST:event_uasKeyTyped

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KHS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField akhir;
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnBersih;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTambah;
    private javax.swing.JTextField huruf;
    private javax.swing.JTextField ips;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jml_sks;
    private javax.swing.JComboBox<String> matkul;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nim;
    private javax.swing.JTextField progdi;
    private javax.swing.JTextField sks;
    private javax.swing.JTable tbl_mhs;
    private javax.swing.JTextField tugas;
    private javax.swing.JTextField uas;
    private javax.swing.JTextField uts;
    // End of variables declaration//GEN-END:variables
}
