/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS;

/**
 *
 * @author LENOVO
 */
public class UAS02801 extends javax.swing.JFrame {

    /**
     * Creates new form UAS02801
     */
    public UAS02801() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        keluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        masterDosen = new javax.swing.JMenuItem();
        masterMahasiswa = new javax.swing.JMenuItem();
        masterMatakul = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        tranKRS = new javax.swing.JMenuItem();
        tranKHS = new javax.swing.JMenuItem();
        tranTran = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplikasi Sistem Informasi Akademik");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setText("File");

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jMenu1.add(keluar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master");

        masterDosen.setText("Dosen");
        masterDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterDosenActionPerformed(evt);
            }
        });
        jMenu2.add(masterDosen);

        masterMahasiswa.setText("Mahasiswa");
        masterMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterMahasiswaActionPerformed(evt);
            }
        });
        jMenu2.add(masterMahasiswa);

        masterMatakul.setText("Mata Kuliah");
        masterMatakul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterMatakulActionPerformed(evt);
            }
        });
        jMenu2.add(masterMatakul);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");

        tranKRS.setText("KRS");
        tranKRS.setToolTipText("");
        tranKRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tranKRSActionPerformed(evt);
            }
        });
        jMenu3.add(tranKRS);

        tranKHS.setText("KHS");
        tranKHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tranKHSActionPerformed(evt);
            }
        });
        jMenu3.add(tranKHS);

        tranTran.setText("Transkrip");
        tranTran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tranTranActionPerformed(evt);
            }
        });
        jMenu3.add(tranTran);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("About");

        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        jMenu4.add(about);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    private void masterDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterDosenActionPerformed
        // TODO add your handling code here:
        new Dosen().setVisible(true);
    }//GEN-LAST:event_masterDosenActionPerformed

    private void masterMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterMahasiswaActionPerformed
        // TODO add your handling code here:
        new Mahasiswa().setVisible(true);
    }//GEN-LAST:event_masterMahasiswaActionPerformed

    private void masterMatakulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterMatakulActionPerformed
        // TODO add your handling code here:
        new MataKuliah().setVisible(true);
    }//GEN-LAST:event_masterMatakulActionPerformed

    private void tranKHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tranKHSActionPerformed
        // TODO add your handling code here:
        new KHS().setVisible(true);
    }//GEN-LAST:event_tranKHSActionPerformed

    private void tranKRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tranKRSActionPerformed
        // TODO add your handling code here:
        new KRS().setVisible(true);
    }//GEN-LAST:event_tranKRSActionPerformed

    private void tranTranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tranTranActionPerformed
        // TODO add your handling code here:
        new Transkrip().setVisible(true);
    }//GEN-LAST:event_tranTranActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
         new About().setVisible(true);
    }//GEN-LAST:event_aboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UAS02801.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UAS02801.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UAS02801.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UAS02801.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UAS02801().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem keluar;
    private javax.swing.JMenuItem masterDosen;
    private javax.swing.JMenuItem masterMahasiswa;
    private javax.swing.JMenuItem masterMatakul;
    private javax.swing.JMenuItem tranKHS;
    private javax.swing.JMenuItem tranKRS;
    private javax.swing.JMenuItem tranTran;
    // End of variables declaration//GEN-END:variables
}
